output "service_account_email" {
  value       = google_service_account.identity_platform_sa.email
  description = "Service account email for Identity Platform"
}

output "default_tenant_id" {
  value       = google_identity_platform_tenant.default.name
  description = "Default tenant ID"
}

output "identity_platform_api_key" {
  value       = "temporary-api-key"  # This will be generated by GCP
  description = "Identity Platform API key"
  sensitive   = true
}